begin;
insert into public.teams
(name, abbr, coach_name, ac_name, conference, division, logo_url, primary_color, secondary_color, wins, losses, ties, points_for, points_against, ppg_for, ppg_against, streak, notes)
values
('Buffalo Bills', 'BUF', '@iancmcclintock', '@Valen59DaGoat', 'AFC', 'AFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png', '#00338D', '#C60C30', 3, 0, 0, 172, 117, 57.33, 39, 'W3', ''),
('Miami Dolphins', 'MIA', '@WydPoison', '@QuixProductions', 'AFC', 'AFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png', '#008E97', '#FC4C02', 2, 1, 0, 147, 124, 49, 41.33, 'W2', ''),
('New England Patriots', 'NE', '@M_JWYouTube', '', 'AFC', 'AFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png', '#002244', '#C60C30', 0, 3, 0, 44, 109, 14.67, 36.33, 'L3', ''),
('New York Jets', 'NYJ', '@Scotclone', '', 'AFC', 'AFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png', '#125740', '#000000', 1, 2, 0, 94, 107, 31.33, 35.67, 'L2', ''),
('Baltimore Ravens', 'BAL', '@H0LLYW00DCARLOS', '@HoodieYo8', 'AFC', 'AFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png', '#241773', '#000000', 0, 3, 0, 110, 277, 36.67, 92.33, 'L3', ''),
('Cincinnati Bengals', 'CIN', '@Dude_Man_11', '@RDukes08', 'AFC', 'AFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png', '#FB4F14', '#000000', 2, 1, 0, 285, 188, 95, 62.67, 'W1', ''),
('Cleveland Browns', 'CLE', '@martinsport2495', '', 'AFC', 'AFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png', '#311D00', '#FF3C00', 1, 2, 0, 118, 278, 39.33, 92.67, 'L1', ''),
('Pittsburgh Steelers', 'PIT', '@Feed_DK', '', 'AFC', 'AFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png', '#101820', '#FFB612', 3, 0, 0, 344, 114, 114.67, 38, 'W3', ''),
('Houston Texans', 'HOU', '@CamIsKing11', '', 'AFC', 'AFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png', '#03202F', '#A71930', 2, 0, 0, 92, 27, 46, 13.5, 'W2', ''),
('Indianapolis Colts', 'IND', '@happystlfan4', '', 'AFC', 'AFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png', '#002C5F', '#A2AAAD', 0, 3, 0, 30, 120, 10, 40, 'L3', ''),
('Jacksonville Jaguars', 'JAX', '@liamcoenszn', '', 'AFC', 'AFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png', '#006778', '#9F792C', 1, 2, 0, 52, 114, 17.33, 38, 'W1', ''),
('Tennessee Titans', 'TEN', '@InformedWatcher', '', 'AFC', 'AFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png', '#0C2340', '#4B92DB', 2, 0, 0, 105, 18, 52.5, 9, 'W2', ''),
('Kansas City Chiefs', 'KC', '@always_chiefs', '@DelanesDomain5', 'AFC', 'AFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png', '#E31837', '#FFB81C', 1, 2, 0, 139, 163, 46.33, 54.33, 'W1', ''),
('Los Angeles Chargers', 'LAC', '@OmarionHamp2', '@PettyPDinero', 'AFC', 'AFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png', '#0080C6', '#FFC20E', 2, 1, 0, 162, 148, 54, 49.33, 'L1', ''),
('Denver Broncos', 'DEN', '@PickedByPS2', '@SurtainGlazer', 'AFC', 'AFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png', '#FB4F14', '#002244', 3, 0, 0, 215, 129, 71.67, 43, 'W3', ''),
('Las Vegas Raiders', 'LV', '@SatansWrathful', '@RAIDERNTFL', 'AFC', 'AFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png', '#000000', '#A5ACAF', 0, 3, 0, 51, 127, 17, 42.33, 'L3', ''),
('Dallas Cowboys', 'DAL', '@ClaytonSkiles', '*NotLikeCeedee', 'NFC', 'NFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png', '#041E42', '#869397', 0, 3, 0, 98, 243, 32.67, 81, 'L3', ''),
('Philadelphia Eagles', 'PHI', '@BraedonMinarik', '@Philliesszn2026', 'NFC', 'NFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png', '#004C54', '#A5ACAF', 2, 0, 0, 216, 99, 108, 49.5, 'W2', ''),
('New York Giants', 'NYG', '@wydpoint', '@Laf4MVP_', 'NFC', 'NFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png', '#0B2265', '#A71930', 2, 0, 0, 151, 64, 75.5, 32, 'W2', ''),
('Washington Commanders', 'WAS', '@Xommanders', '@NateBG_22', 'NFC', 'NFC East', 'https://a.espncdn.com/i/teamlogos/nfl/500/was.png', '#5A1414', '#FFB612', 1, 2, 0, 129, 188, 43, 62.67, 'W1', ''),
('Detroit Lions', 'DET', '@MossedBySunGod', '', 'NFC', 'NFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png', '#0076B6', '#B0B7BC', 1, 2, 0, 77, 98, 25.67, 32.67, 'L1', ''),
('Green Bay Packers', 'GB', '@bug49_', '@NotOnGodOnRodge', 'NFC', 'NFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png', '#203731', '#FFB612', 2, 1, 0, 90, 73, 30, 24.33, 'W1', ''),
('Minnesota Vikings', 'MIN', '@GarganoSzn1', '', 'NFC', 'NFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png', '#4F2683', '#FFC62F', 3, 0, 0, 107, 35, 35.67, 11.67, 'W3', ''),
('Chicago Bears', 'CHI', '@burdenszn', '', 'NFC', 'NFC North', 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png', '#0B162A', '#C83803', 0, 3, 0, 35, 103, 11.67, 34.33, 'L3', ''),
('Tampa Bay Buccaneers', 'TB', '@bucsnationx210', '', 'NFC', 'NFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png', '#D50A0A', '#34302B', 1, 2, 0, 79, 94, 26.33, 31.33, 'L2', ''),
('Atlanta Falcons', 'ATL', '@grae_visocan', '', 'NFC', 'NFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png', '#A71930', '#000000', 0, 3, 0, 46, 124, 15.33, 41.33, 'L3', ''),
('New Orleans Saints', 'NO', '@ThomasBart17127', '@ihykronos', 'NFC', 'NFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png', '#D3BC8D', '#101820', 3, 0, 0, 168, 84, 56, 28, 'W3', ''),
('Carolina Panthers', 'CAR', '@gabriel_ki4939', '', 'NFC', 'NFC South', 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png', '#0085CA', '#101820', 2, 1, 0, 84, 75, 28, 25, 'W2', ''),
('San Francisco 49ers', 'SF', '@Ty_C13', '', 'NFC', 'NFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png', '#AA0000', '#B3995D', 0, 3, 0, 32, 110, 10.67, 36.67, 'L3', ''),
('Seattle Seahawks', 'SEA', '@wardangsports88', '@gregheffley2011', 'NFC', 'NFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png', '#002244', '#69BE28', 3, 0, 0, 164, 47, 54.67, 15.67, 'W3', ''),
('Los Angeles Rams', 'LAR', '@Bucsfan6to13', '@ChickenNinja42', 'NFC', 'NFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png', '#003594', '#FFA300', 2, 1, 0, 73, 95, 24.33, 31.67, 'L1', ''),
('Arizona Cardinals', 'ARI', '@watts__53', '', 'NFC', 'NFC West', 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png', '#97233F', '#000000', 1, 2, 0, 86, 103, 28.67, 34.33, 'W1', '');

insert into public.schedule_games
(id, week, week_number, game_date, kickoff_time, home_team_name, away_team_name, home_score, away_score, status, is_live, spotlight, source_sheet, note)
values
('w1-seahawks-at-49ers', 'W1', 1, null, null, 'San Francisco 49ers', 'Seattle Seahawks', 13, 62, 'final', false, null, 'NFC West', null),
('w1-dolphins-at-bills', 'W1', 1, null, null, 'Buffalo Bills', 'Miami Dolphins', 85, 83, 'final', false, null, 'AFC East', null),
('w1-chiefs-at-broncos', 'W1', 1, null, null, 'Denver Broncos', 'Kansas City Chiefs', 90, 52, 'final', false, null, 'AFC West', null),
('w1-steelers-at-browns', 'W1', 1, null, null, 'Cleveland Browns', 'Pittsburgh Steelers', 61, 127, 'final', false, null, 'AFC North', null),
('w1-falcons-at-buccaneers', 'W1', 1, null, null, 'Tampa Bay Buccaneers', 'Atlanta Falcons', 24, 21, 'final', false, null, 'NFC South', null),
('w1-giants-at-cowboys', 'W1', 1, null, null, 'Dallas Cowboys', 'New York Giants', 47, 105, 'final', false, null, 'NFC East', null),
('w1-commanders-at-eagles', 'W1', 1, null, null, 'Philadelphia Eagles', 'Washington Commanders', 112, 78, 'final', false, null, 'NFC East', null),
('w1-titans-at-jaguars', 'W1', 1, null, null, 'Jacksonville Jaguars', 'Tennessee Titans', 10, 70, 'final', false, null, 'AFC South', null),
('w1-lions-at-packers', 'W1', 1, null, null, 'Green Bay Packers', 'Detroit Lions', 49, 39, 'final', false, null, 'NFC North', null),
('w1-jets-at-patriots', 'W1', 1, null, null, 'New England Patriots', 'New York Jets', 26, 39, 'final', false, null, 'AFC East', null),
('w1-chargers-at-raiders', 'W1', 1, null, null, 'Las Vegas Raiders', 'Los Angeles Chargers', 15, 48, 'final', false, null, 'AFC West', null),
('w1-cardinals-at-rams', 'W1', 1, null, null, 'Los Angeles Rams', 'Arizona Cardinals', 42, 35, 'final', false, null, 'NFC West', null),
('w1-bengals-at-ravens', 'W1', 1, null, null, 'Baltimore Ravens', 'Cincinnati Bengals', 62, 129, 'final', false, null, 'AFC North', null),
('w1-panthers-at-saints', 'W1', 1, null, null, 'New Orleans Saints', 'Carolina Panthers', 41, 38, 'final', false, true, 'NFC South', 'OT'),
('w1-colts-at-texans', 'W1', 1, null, null, 'Houston Texans', 'Indianapolis Colts', 54, 16, 'final', false, null, 'AFC South', null),
('w1-bears-at-vikings', 'W1', 1, null, null, 'Minnesota Vikings', 'Chicago Bears', 43, 16, 'final', false, null, 'NFC North', null),
('w2-rams-at-49ers', 'W2', 2, null, null, 'San Francisco 49ers', 'Los Angeles Rams', 11, 18, 'final', false, null, 'NFC West', null),
('w2-steelers-at-bengals', 'W2', 2, null, null, 'Cincinnati Bengals', 'Pittsburgh Steelers', 35, 105, 'final', false, null, 'AFC North', null),
('w2-patriots-at-bills', 'W2', 2, null, null, 'Buffalo Bills', 'New England Patriots', 39, 10, 'final', false, null, 'AFC East', null),
('w2-raiders-at-broncos', 'W2', 2, null, null, 'Denver Broncos', 'Las Vegas Raiders', 39, 25, 'final', false, null, 'AFC West', null),
('w2-saints-at-buccaneers', 'W2', 2, null, null, 'Tampa Bay Buccaneers', 'New Orleans Saints', 38, 45, 'final', false, null, 'NFC South', null),
('w2-chargers-at-chiefs', 'W2', 2, null, null, 'Kansas City Chiefs', 'Los Angeles Chargers', 47, 62, 'final', false, null, 'AFC West', null),
('w2-titans-at-colts', 'W2', 2, null, null, 'Indianapolis Colts', 'Tennessee Titans', 8, 35, 'final', false, null, 'AFC South', null),
('w2-eagles-at-cowboys', 'W2', 2, null, null, 'Dallas Cowboys', 'Philadelphia Eagles', 21, 104, 'final', false, null, 'NFC East', null),
('w2-jets-at-dolphins', 'W2', 2, null, null, 'Miami Dolphins', 'New York Jets', 33, 31, 'final', false, null, 'AFC East', null),
('w2-panthers-at-falcons', 'W2', 2, null, null, 'Atlanta Falcons', 'Carolina Panthers', 17, 18, 'final', false, null, 'NFC South', null),
('w2-commanders-at-giants', 'W2', 2, null, null, 'New York Giants', 'Washington Commanders', 46, 17, 'final', false, null, 'NFC East', null),
('w2-bears-at-lions', 'W2', 2, null, null, 'Detroit Lions', 'Chicago Bears', 29, 8, 'final', false, null, 'NFC North', null),
('w2-vikings-at-packers', 'W2', 2, null, null, 'Green Bay Packers', 'Minnesota Vikings', 10, 23, 'final', false, null, 'NFC North', null),
('w2-browns-at-ravens', 'W2', 2, null, null, 'Baltimore Ravens', 'Cleveland Browns', 30, 36, 'final', false, null, 'AFC North', null),
('w2-cardinals-at-seahawks', 'W2', 2, null, null, 'Seattle Seahawks', 'Arizona Cardinals', 53, 21, 'final', false, null, 'NFC West', null),
('w2-jaguars-at-texans', 'W2', 2, null, null, 'Houston Texans', 'Jacksonville Jaguars', 38, 11, 'final', false, null, 'AFC South', null),
('w3-cardinals-at-49ers', 'W3', 3, null, null, 'San Francisco 49ers', 'Arizona Cardinals', 8, 30, 'final', false, null, 'NFC West', null),
('w3-browns-at-bengals', 'W3', 3, null, null, 'Cincinnati Bengals', 'Cleveland Browns', 121, 21, 'final', false, null, 'AFC North', null),
('w3-jets-at-bills', 'W3', 3, null, null, 'Buffalo Bills', 'New York Jets', 48, 24, 'final', false, null, 'AFC East', null),
('w3-chargers-at-broncos', 'W3', 3, null, null, 'Denver Broncos', 'Los Angeles Chargers', 86, 52, 'final', false, null, 'AFC West', null),
('w3-panthers-at-buccaneers', 'W3', 3, null, null, 'Tampa Bay Buccaneers', 'Carolina Panthers', 17, 28, 'final', false, null, 'NFC South', null),
('w3-raiders-at-chiefs', 'W3', 3, null, null, 'Kansas City Chiefs', 'Las Vegas Raiders', 40, 11, 'final', false, null, 'AFC West', null),
('w3-jaguars-at-colts', 'W3', 3, null, null, 'Indianapolis Colts', 'Jacksonville Jaguars', 6, 31, 'final', false, null, 'AFC South', null),
('w3-commanders-at-cowboys', 'W3', 3, null, null, 'Dallas Cowboys', 'Washington Commanders', 30, 34, 'final', false, null, 'NFC East', null),
('w3-patriots-at-dolphins', 'W3', 3, null, null, 'Miami Dolphins', 'New England Patriots', 31, 8, 'final', false, null, 'AFC East', null),
('w3-saints-at-falcons', 'W3', 3, null, null, 'Atlanta Falcons', 'New Orleans Saints', 8, 82, 'final', false, null, 'NFC South', null),
('w3-eagles-at-giants', 'W3', 3, null, null, 'New York Giants', 'Philadelphia Eagles', null, null, 'scheduled', false, true, 'NFC East', 'SNF'),
('w3-vikings-at-lions', 'W3', 3, null, null, 'Detroit Lions', 'Minnesota Vikings', 9, 41, 'final', false, null, 'NFC North', null),
('w3-bears-at-packers', 'W3', 3, null, null, 'Green Bay Packers', 'Chicago Bears', 31, 11, 'final', false, null, 'NFC North', null),
('w3-steelers-at-ravens', 'W3', 3, null, null, 'Baltimore Ravens', 'Pittsburgh Steelers', 18, 112, 'final', false, null, 'AFC North', null),
('w3-rams-at-seahawks', 'W3', 3, null, null, 'Seattle Seahawks', 'Los Angeles Rams', 49, 13, 'final', false, true, 'NFC West', null),
('w3-titans-at-texans', 'W3', 3, null, null, 'Houston Texans', 'Tennessee Titans', null, null, 'scheduled', false, true, 'AFC South', 'MNF'),
('w4-chiefs-at-buccaneers', 'W4', 4, null, null, 'Tampa Bay Buccaneers', 'Kansas City Chiefs', null, null, 'scheduled', false, null, 'AFC West', null),
('w4-commanders-at-cardinals', 'W4', 4, null, null, 'Arizona Cardinals', 'Washington Commanders', null, null, 'scheduled', false, true, 'NFC East', 'TNF'),
('w4-panthers-at-cowboys', 'W4', 4, null, null, 'Dallas Cowboys', 'Carolina Panthers', null, null, 'scheduled', false, true, 'NFC East', 'SNF'),
('w4-chargers-at-eagles', 'W4', 4, null, null, 'Philadelphia Eagles', 'Los Angeles Chargers', null, null, 'scheduled', false, null, 'AFC West', null),
('w4-seahawks-at-falcons', 'W4', 4, null, null, 'Atlanta Falcons', 'Seattle Seahawks', null, null, 'scheduled', false, null, 'NFC South', null),
('w4-lions-at-giants', 'W4', 4, null, null, 'New York Giants', 'Detroit Lions', null, null, 'scheduled', false, null, 'NFC East', null),
('w4-bears-at-jaguars', 'W4', 4, null, null, 'Jacksonville Jaguars', 'Chicago Bears', null, null, 'scheduled', false, null, 'AFC South', null),
('w4-browns-at-packers', 'W4', 4, null, null, 'Green Bay Packers', 'Cleveland Browns', null, null, 'scheduled', false, null, 'AFC North', null),
('w4-titans-at-raiders', 'W4', 4, null, null, 'Las Vegas Raiders', 'Tennessee Titans', null, null, 'scheduled', false, null, 'AFC South', null),
('w4-colts-at-rams', 'W4', 4, null, null, 'Los Angeles Rams', 'Indianapolis Colts', null, null, 'scheduled', false, null, 'AFC South', null),
('w4-broncos-at-ravens', 'W4', 4, null, null, 'Baltimore Ravens', 'Denver Broncos', null, null, 'scheduled', false, null, 'AFC North', null),
('w4-steelers-at-saints', 'W4', 4, null, null, 'New Orleans Saints', 'Pittsburgh Steelers', null, null, 'scheduled', false, null, 'AFC North', null),
('w4-bengals-at-texans', 'W4', 4, null, null, 'Houston Texans', 'Cincinnati Bengals', null, null, 'scheduled', false, true, 'AFC North', 'MNF'),
('w4-49ers-at-vikings', 'W4', 4, null, null, 'Minnesota Vikings', 'San Francisco 49ers', null, null, 'scheduled', false, null, 'NFC North', null),
('w5-jets-at-bears', 'W5', 5, null, null, 'Chicago Bears', 'New York Jets', null, null, 'scheduled', false, null, 'AFC East', null),
('w5-colts-at-broncos', 'W5', 5, null, null, 'Denver Broncos', 'Indianapolis Colts', null, null, 'scheduled', false, true, 'AFC South', 'SNF'),
('w5-patriots-at-buccaneers', 'W5', 5, null, null, 'Tampa Bay Buccaneers', 'New England Patriots', null, null, 'scheduled', false, null, 'AFC East', null),
('w5-eagles-at-cardinals', 'W5', 5, null, null, 'Arizona Cardinals', 'Philadelphia Eagles', null, null, 'scheduled', false, null, 'NFC East', null),
('w5-raiders-at-cowboys', 'W5', 5, null, null, 'Dallas Cowboys', 'Las Vegas Raiders', null, null, 'scheduled', false, null, 'AFC West', null),
('w5-packers-at-dolphins', 'W5', 5, null, null, 'Miami Dolphins', 'Green Bay Packers', null, null, 'scheduled', false, true, 'AFC East', 'TNF'),
('w5-jaguars-at-giants', 'W5', 5, null, null, 'New York Giants', 'Jacksonville Jaguars', null, null, 'scheduled', false, null, 'AFC South', null),
('w5-chargers-at-lions', 'W5', 5, null, null, 'Detroit Lions', 'Los Angeles Chargers', null, null, 'scheduled', false, null, 'AFC West', null),
('w5-chiefs-at-panthers', 'W5', 5, null, null, 'Carolina Panthers', 'Kansas City Chiefs', null, null, 'scheduled', false, null, 'AFC West', null),
('w5-vikings-at-rams', 'W5', 5, null, null, 'Los Angeles Rams', 'Minnesota Vikings', null, null, 'scheduled', false, null, 'NFC North', null),
('w5-commanders-at-saints', 'W5', 5, null, null, 'New Orleans Saints', 'Washington Commanders', null, null, 'scheduled', false, null, 'NFC East', null),
('w5-bills-at-seahawks', 'W5', 5, null, null, 'Seattle Seahawks', 'Buffalo Bills', null, null, 'scheduled', false, null, 'AFC East', null),
('w5-49ers-at-texans', 'W5', 5, null, null, 'Houston Texans', 'San Francisco 49ers', null, null, 'scheduled', false, null, 'AFC South', null),
('w5-falcons-at-titans', 'W5', 5, null, null, 'Tennessee Titans', 'Atlanta Falcons', null, null, 'scheduled', false, true, 'AFC South', 'MNF'),
('w6-eagles-at-49ers', 'W6', 6, null, null, 'San Francisco 49ers', 'Philadelphia Eagles', null, null, 'scheduled', false, null, 'NFC East', null),
('w6-broncos-at-bears', 'W6', 6, null, null, 'Chicago Bears', 'Denver Broncos', null, null, 'scheduled', false, null, 'AFC West', null),
('w6-falcons-at-bengals', 'W6', 6, null, null, 'Cincinnati Bengals', 'Atlanta Falcons', null, null, 'scheduled', false, null, 'AFC North', null),
('w6-buccaneers-at-bills', 'W6', 6, null, null, 'Buffalo Bills', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, null, 'AFC East', null),
('w6-giants-at-browns', 'W6', 6, null, null, 'Cleveland Browns', 'New York Giants', null, null, 'scheduled', false, true, 'AFC North', 'TNF'),
('w6-ravens-at-chargers', 'W6', 6, null, null, 'Los Angeles Chargers', 'Baltimore Ravens', null, null, 'scheduled', false, true, 'AFC North', 'SNF'),
('w6-rams-at-chiefs', 'W6', 6, null, null, 'Kansas City Chiefs', 'Los Angeles Rams', null, null, 'scheduled', false, null, 'AFC West', null),
('w6-dolphins-at-cowboys', 'W6', 6, null, null, 'Dallas Cowboys', 'Miami Dolphins', null, null, 'scheduled', false, null, 'AFC East', null),
('w6-packers-at-jets', 'W6', 6, null, null, 'New York Jets', 'Green Bay Packers', null, null, 'scheduled', false, null, 'AFC East', null),
('w6-raiders-at-lions', 'W6', 6, null, null, 'Detroit Lions', 'Las Vegas Raiders', null, null, 'scheduled', false, true, 'AFC West', 'MNF'),
('w6-commanders-at-patriots', 'W6', 6, null, null, 'New England Patriots', 'Washington Commanders', null, null, 'scheduled', false, null, 'AFC East', null),
('w6-saints-at-seahawks', 'W6', 6, null, null, 'Seattle Seahawks', 'New Orleans Saints', null, null, 'scheduled', false, null, 'NFC South', null),
('w6-panthers-at-steelers', 'W6', 6, null, null, 'Pittsburgh Steelers', 'Carolina Panthers', null, null, 'scheduled', false, null, 'AFC North', null),
('w6-cardinals-at-vikings', 'W6', 6, null, null, 'Minnesota Vikings', 'Arizona Cardinals', null, null, 'scheduled', false, null, 'NFC North', null),
('w7-cowboys-at-bengals', 'W7', 7, null, null, 'Cincinnati Bengals', 'Dallas Cowboys', null, null, 'scheduled', false, null, 'AFC North', null),
('w7-panthers-at-bills', 'W7', 7, null, null, 'Buffalo Bills', 'Carolina Panthers', null, null, 'scheduled', false, null, 'AFC East', null),
('w7-colts-at-cardinals', 'W7', 7, null, null, 'Arizona Cardinals', 'Indianapolis Colts', null, null, 'scheduled', false, null, 'AFC South', null),
('w7-browns-at-commanders', 'W7', 7, null, null, 'Washington Commanders', 'Cleveland Browns', null, null, 'scheduled', false, null, 'AFC North', null),
('w7-eagles-at-dolphins', 'W7', 7, null, null, 'Miami Dolphins', 'Philadelphia Eagles', null, null, 'scheduled', false, null, 'AFC East', null),
('w7-giants-at-falcons', 'W7', 7, null, null, 'Atlanta Falcons', 'New York Giants', null, null, 'scheduled', false, null, 'NFC East', null),
('w7-packers-at-jaguars', 'W7', 7, null, null, 'Jacksonville Jaguars', 'Green Bay Packers', null, null, 'scheduled', false, true, 'AFC South', 'MNF'),
('w7-steelers-at-lions', 'W7', 7, null, null, 'Detroit Lions', 'Pittsburgh Steelers', null, null, 'scheduled', false, null, 'AFC North', null),
('w7-bears-at-patriots', 'W7', 7, null, null, 'New England Patriots', 'Chicago Bears', null, null, 'scheduled', false, true, 'AFC East', 'TNF'),
('w7-seahawks-at-ravens', 'W7', 7, null, null, 'Baltimore Ravens', 'Seattle Seahawks', null, null, 'scheduled', false, null, 'AFC North', null),
('w7-49ers-at-saints', 'W7', 7, null, null, 'New Orleans Saints', 'San Francisco 49ers', null, null, 'scheduled', false, null, 'NFC South', null),
('w7-rams-at-texans', 'W7', 7, null, null, 'Houston Texans', 'Los Angeles Rams', null, null, 'scheduled', false, true, 'AFC South', 'SNF'),
('w7-buccaneers-at-titans', 'W7', 7, null, null, 'Tennessee Titans', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, null, 'AFC South', null),
('w7-jets-at-vikings', 'W7', 7, null, null, 'Minnesota Vikings', 'New York Jets', null, null, 'scheduled', false, null, 'AFC East', null),
('w8-packers-at-bills', 'W8', 8, null, null, 'Buffalo Bills', 'Green Bay Packers', null, null, 'scheduled', false, null, 'AFC East', null),
('w8-buccaneers-at-browns', 'W8', 8, null, null, 'Cleveland Browns', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, null, 'AFC North', null),
('w8-panthers-at-chargers', 'W8', 8, null, null, 'Los Angeles Chargers', 'Carolina Panthers', null, null, 'scheduled', false, null, 'AFC West', null),
('w8-commanders-at-chiefs', 'W8', 8, null, null, 'Kansas City Chiefs', 'Washington Commanders', null, null, 'scheduled', false, true, 'AFC West', 'SNF'),
('w8-falcons-at-colts', 'W8', 8, null, null, 'Indianapolis Colts', 'Atlanta Falcons', null, null, 'scheduled', false, null, 'AFC South', null),
('w8-vikings-at-dolphins', 'W8', 8, null, null, 'Miami Dolphins', 'Minnesota Vikings', null, null, 'scheduled', false, null, 'AFC East', null),
('w8-patriots-at-eagles', 'W8', 8, null, null, 'Philadelphia Eagles', 'New England Patriots', null, null, 'scheduled', false, null, 'AFC East', null),
('w8-rams-at-jaguars', 'W8', 8, null, null, 'Jacksonville Jaguars', 'Los Angeles Rams', null, null, 'scheduled', false, true, 'AFC South', 'TNF'),
('w8-broncos-at-jets', 'W8', 8, null, null, 'New York Jets', 'Denver Broncos', null, null, 'scheduled', false, null, 'AFC East', null),
('w8-49ers-at-lions', 'W8', 8, null, null, 'Detroit Lions', 'San Francisco 49ers', null, null, 'scheduled', false, null, 'NFC North', null),
('w8-bengals-at-raiders', 'W8', 8, null, null, 'Las Vegas Raiders', 'Cincinnati Bengals', null, null, 'scheduled', false, null, 'AFC North', null),
('w8-cardinals-at-ravens', 'W8', 8, null, null, 'Baltimore Ravens', 'Arizona Cardinals', null, null, 'scheduled', false, null, 'AFC North', null),
('w8-titans-at-saints', 'W8', 8, null, null, 'New Orleans Saints', 'Tennessee Titans', null, null, 'scheduled', false, true, 'AFC South', 'MNF'),
('w8-texans-at-seahawks', 'W8', 8, null, null, 'Seattle Seahawks', 'Houston Texans', null, null, 'scheduled', false, null, 'AFC South', null),
('w8-bears-at-steelers', 'W8', 8, null, null, 'Pittsburgh Steelers', 'Chicago Bears', null, null, 'scheduled', false, null, 'AFC North', null),
('w9-dolphins-at-49ers', 'W9', 9, null, null, 'San Francisco 49ers', 'Miami Dolphins', null, null, 'scheduled', false, true, 'AFC East', 'SNF'),
('w9-colts-at-bears', 'W9', 9, null, null, 'Chicago Bears', 'Indianapolis Colts', null, null, 'scheduled', false, null, 'AFC South', null),
('w9-cardinals-at-bengals', 'W9', 9, null, null, 'Cincinnati Bengals', 'Arizona Cardinals', null, null, 'scheduled', false, null, 'AFC North', null),
('w9-cowboys-at-browns', 'W9', 9, null, null, 'Cleveland Browns', 'Dallas Cowboys', null, null, 'scheduled', false, null, 'AFC North', null),
('w9-rams-at-buccaneers', 'W9', 9, null, null, 'Tampa Bay Buccaneers', 'Los Angeles Rams', null, null, 'scheduled', false, null, 'NFC South', null),
('w9-falcons-at-chargers', 'W9', 9, null, null, 'Los Angeles Chargers', 'Atlanta Falcons', null, null, 'scheduled', false, true, 'AFC West', 'MNF'),
('w9-titans-at-giants', 'W9', 9, null, null, 'New York Giants', 'Tennessee Titans', null, null, 'scheduled', false, null, 'AFC South', null),
('w9-bills-at-jaguars', 'W9', 9, null, null, 'Jacksonville Jaguars', 'Buffalo Bills', null, null, 'scheduled', false, null, 'AFC East', null),
('w9-raiders-at-jets', 'W9', 9, null, null, 'New York Jets', 'Las Vegas Raiders', null, null, 'scheduled', false, null, 'AFC East', null),
('w9-texans-at-lions', 'W9', 9, null, null, 'Detroit Lions', 'Houston Texans', null, null, 'scheduled', false, null, 'AFC South', null),
('w9-ravens-at-packers', 'W9', 9, null, null, 'Green Bay Packers', 'Baltimore Ravens', null, null, 'scheduled', false, null, 'AFC North', null),
('w9-broncos-at-panthers', 'W9', 9, null, null, 'Carolina Panthers', 'Denver Broncos', null, null, 'scheduled', false, null, 'AFC West', null),
('w9-saints-at-patriots', 'W9', 9, null, null, 'New England Patriots', 'New Orleans Saints', null, null, 'scheduled', false, null, 'AFC East', null),
('w9-chiefs-at-seahawks', 'W9', 9, null, null, 'Seattle Seahawks', 'Kansas City Chiefs', null, null, 'scheduled', false, null, 'AFC West', null),
('w9-vikings-at-steelers', 'W9', 9, null, null, 'Pittsburgh Steelers', 'Minnesota Vikings', null, null, 'scheduled', false, true, 'AFC North', 'TNF'),
('w10-colts-at-49ers', 'W10', 10, null, null, 'San Francisco 49ers', 'Indianapolis Colts', null, null, 'scheduled', false, null, 'AFC South', null),
('w10-chargers-at-bills', 'W10', 10, null, null, 'Buffalo Bills', 'Los Angeles Chargers', null, null, 'scheduled', false, null, 'AFC East', null),
('w10-saints-at-broncos', 'W10', 10, null, null, 'Denver Broncos', 'New Orleans Saints', null, null, 'scheduled', false, null, 'AFC West', null),
('w10-seahawks-at-buccaneers', 'W10', 10, null, null, 'Tampa Bay Buccaneers', 'Seattle Seahawks', null, null, 'scheduled', false, true, 'NFC South', 'SNF'),
('w10-dolphins-at-cardinals', 'W10', 10, null, null, 'Arizona Cardinals', 'Miami Dolphins', null, null, 'scheduled', false, null, 'AFC East', null),
('w10-eagles-at-chiefs', 'W10', 10, null, null, 'Kansas City Chiefs', 'Philadelphia Eagles', null, null, 'scheduled', false, null, 'AFC West', null),
('w10-jaguars-at-commanders', 'W10', 10, null, null, 'Washington Commanders', 'Jacksonville Jaguars', null, null, 'scheduled', false, true, 'AFC South', 'TNF'),
('w10-jets-at-cowboys', 'W10', 10, null, null, 'Dallas Cowboys', 'New York Jets', null, null, 'scheduled', false, null, 'AFC East', null),
('w10-steelers-at-falcons', 'W10', 10, null, null, 'Atlanta Falcons', 'Pittsburgh Steelers', null, null, 'scheduled', false, null, 'AFC North', null),
('w10-ravens-at-giants', 'W10', 10, null, null, 'New York Giants', 'Baltimore Ravens', null, null, 'scheduled', false, true, 'AFC North', 'MNF'),
('w10-texans-at-panthers', 'W10', 10, null, null, 'Carolina Panthers', 'Houston Texans', null, null, 'scheduled', false, null, 'AFC South', null),
('w10-browns-at-raiders', 'W10', 10, null, null, 'Las Vegas Raiders', 'Cleveland Browns', null, null, 'scheduled', false, null, 'AFC North', null),
('w10-bengals-at-rams', 'W10', 10, null, null, 'Los Angeles Rams', 'Cincinnati Bengals', null, null, 'scheduled', false, null, 'AFC North', null),
('w10-bears-at-titans', 'W10', 10, null, null, 'Tennessee Titans', 'Chicago Bears', null, null, 'scheduled', false, null, 'AFC South', null),
('w10-patriots-at-vikings', 'W10', 10, null, null, 'Minnesota Vikings', 'New England Patriots', null, null, 'scheduled', false, null, 'AFC East', null),
('w11-cowboys-at-bills', 'W11', 11, null, null, 'Buffalo Bills', 'Dallas Cowboys', null, null, 'scheduled', false, null, 'AFC East', null),
('w11-falcons-at-broncos', 'W11', 11, null, null, 'Denver Broncos', 'Atlanta Falcons', null, null, 'scheduled', false, true, 'AFC West', 'MNF'),
('w11-jets-at-buccaneers', 'W11', 11, null, null, 'Tampa Bay Buccaneers', 'New York Jets', null, null, 'scheduled', false, null, 'AFC East', null),
('w11-chiefs-at-cardinals', 'W11', 11, null, null, 'Arizona Cardinals', 'Kansas City Chiefs', null, null, 'scheduled', false, null, 'AFC West', null),
('w11-jaguars-at-chargers', 'W11', 11, null, null, 'Los Angeles Chargers', 'Jacksonville Jaguars', null, null, 'scheduled', false, null, 'AFC South', null),
('w11-eagles-at-colts', 'W11', 11, null, null, 'Indianapolis Colts', 'Philadelphia Eagles', null, null, 'scheduled', false, true, 'AFC South', 'SNF'),
('w11-lions-at-commanders', 'W11', 11, null, null, 'Washington Commanders', 'Detroit Lions', null, null, 'scheduled', false, null, 'NFC East', null),
('w11-rams-at-dolphins', 'W11', 11, null, null, 'Miami Dolphins', 'Los Angeles Rams', null, null, 'scheduled', false, null, 'AFC East', null),
('w11-saints-at-giants', 'W11', 11, null, null, 'New York Giants', 'New Orleans Saints', null, null, 'scheduled', false, null, 'NFC East', null),
('w11-bengals-at-packers', 'W11', 11, null, null, 'Green Bay Packers', 'Cincinnati Bengals', null, null, 'scheduled', false, null, 'AFC North', null),
('w11-raiders-at-panthers', 'W11', 11, null, null, 'Carolina Panthers', 'Las Vegas Raiders', null, null, 'scheduled', false, true, 'AFC West', 'TNF'),
('w11-seahawks-at-patriots', 'W11', 11, null, null, 'New England Patriots', 'Seattle Seahawks', null, null, 'scheduled', false, null, 'AFC East', null),
('w11-texans-at-ravens', 'W11', 11, null, null, 'Baltimore Ravens', 'Houston Texans', null, null, 'scheduled', false, null, 'AFC North', null),
('w11-49ers-at-steelers', 'W11', 11, null, null, 'Pittsburgh Steelers', 'San Francisco 49ers', null, null, 'scheduled', false, null, 'AFC North', null),
('w11-browns-at-titans', 'W11', 11, null, null, 'Tennessee Titans', 'Cleveland Browns', null, null, 'scheduled', false, null, 'AFC North', null),
('w12-bengals-at-49ers', 'W12', 12, null, null, 'San Francisco 49ers', 'Cincinnati Bengals', null, null, 'scheduled', false, null, 'AFC North', null),
('w12-bills-at-bears', 'W12', 12, null, null, 'Chicago Bears', 'Buffalo Bills', null, null, 'scheduled', false, null, 'AFC East', null),
('w12-lions-at-broncos', 'W12', 12, null, null, 'Denver Broncos', 'Detroit Lions', null, null, 'scheduled', false, true, 'AFC West', 'SNF'),
('w12-browns-at-chiefs', 'W12', 12, null, null, 'Kansas City Chiefs', 'Cleveland Browns', null, null, 'scheduled', false, null, 'AFC North', null),
('w12-cowboys-at-colts', 'W12', 12, null, null, 'Indianapolis Colts', 'Dallas Cowboys', null, null, 'scheduled', false, null, 'AFC South', null),
('w12-seahawks-at-dolphins', 'W12', 12, null, null, 'Miami Dolphins', 'Seattle Seahawks', null, null, 'scheduled', false, null, 'AFC East', null),
('w12-jaguars-at-eagles', 'W12', 12, null, null, 'Philadelphia Eagles', 'Jacksonville Jaguars', null, null, 'scheduled', false, null, 'AFC South', null),
('w12-vikings-at-giants', 'W12', 12, null, null, 'New York Giants', 'Minnesota Vikings', null, null, 'scheduled', false, null, 'NFC East', null),
('w12-chargers-at-jets', 'W12', 12, null, null, 'New York Jets', 'Los Angeles Chargers', null, null, 'scheduled', false, true, 'AFC East', 'MNF'),
('w12-texans-at-packers', 'W12', 12, null, null, 'Green Bay Packers', 'Houston Texans', null, null, 'scheduled', false, null, 'AFC South', null),
('w12-patriots-at-panthers', 'W12', 12, null, null, 'Carolina Panthers', 'New England Patriots', null, null, 'scheduled', false, null, 'AFC East', null),
('w12-rams-at-raiders', 'W12', 12, null, null, 'Las Vegas Raiders', 'Los Angeles Rams', null, null, 'scheduled', false, null, 'AFC West', null),
('w12-saints-at-ravens', 'W12', 12, null, null, 'Baltimore Ravens', 'New Orleans Saints', null, null, 'scheduled', false, true, 'AFC North', 'TNF'),
('w12-cardinals-at-steelers', 'W12', 12, null, null, 'Pittsburgh Steelers', 'Arizona Cardinals', null, null, 'scheduled', false, null, 'AFC North', null),
('w12-commanders-at-titans', 'W12', 12, null, null, 'Tennessee Titans', 'Washington Commanders', null, null, 'scheduled', false, null, 'AFC South', null),
('w13-chiefs-at-49ers', 'W13', 13, null, null, 'San Francisco 49ers', 'Kansas City Chiefs', null, null, 'scheduled', false, null, 'AFC West', null),
('w13-chargers-at-bengals', 'W13', 13, null, null, 'Cincinnati Bengals', 'Los Angeles Chargers', null, null, 'scheduled', false, null, 'AFC North', null),
('w13-lions-at-bills', 'W13', 13, null, null, 'Buffalo Bills', 'Detroit Lions', null, null, 'scheduled', false, null, 'AFC East', null),
('w13-browns-at-broncos', 'W13', 13, null, null, 'Denver Broncos', 'Cleveland Browns', null, null, 'scheduled', false, null, 'AFC North', null),
('w13-cardinals-at-buccaneers', 'W13', 13, null, null, 'Tampa Bay Buccaneers', 'Arizona Cardinals', null, null, 'scheduled', false, null, 'NFC South', null),
('w13-giants-at-colts', 'W13', 13, null, null, 'Indianapolis Colts', 'New York Giants', null, null, 'scheduled', false, null, 'AFC South', null),
('w13-dolphins-at-commanders', 'W13', 13, null, null, 'Washington Commanders', 'Miami Dolphins', null, null, 'scheduled', false, true, 'AFC East', 'MNF'),
('w13-titans-at-cowboys', 'W13', 13, null, null, 'Dallas Cowboys', 'Tennessee Titans', null, null, 'scheduled', false, null, 'AFC South', null),
('w13-jets-at-eagles', 'W13', 13, null, null, 'Philadelphia Eagles', 'New York Jets', null, null, 'scheduled', false, null, 'AFC East', null),
('w13-jaguars-at-falcons', 'W13', 13, null, null, 'Atlanta Falcons', 'Jacksonville Jaguars', null, null, 'scheduled', false, null, 'AFC South', null),
('w13-patriots-at-packers', 'W13', 13, null, null, 'Green Bay Packers', 'New England Patriots', null, null, 'scheduled', false, null, 'AFC East', null),
('w13-ravens-at-raiders', 'W13', 13, null, null, 'Las Vegas Raiders', 'Baltimore Ravens', null, null, 'scheduled', false, null, 'AFC North', null),
('w13-steelers-at-rams', 'W13', 13, null, null, 'Los Angeles Rams', 'Pittsburgh Steelers', null, null, 'scheduled', false, true, 'AFC North', 'SNF'),
('w13-vikings-at-seahawks', 'W13', 13, null, null, 'Seattle Seahawks', 'Minnesota Vikings', null, null, 'scheduled', false, null, 'NFC North', null),
('w13-bears-at-texans', 'W13', 13, null, null, 'Houston Texans', 'Chicago Bears', null, null, 'scheduled', false, true, 'AFC South', 'TNF'),
('w14-dolphins-at-bears', 'W14', 14, null, null, 'Chicago Bears', 'Miami Dolphins', null, null, 'scheduled', false, null, 'AFC East', null),
('w14-broncos-at-bengals', 'W14', 14, null, null, 'Cincinnati Bengals', 'Denver Broncos', null, null, 'scheduled', false, null, 'AFC North', null),
('w14-eagles-at-browns', 'W14', 14, null, null, 'Cleveland Browns', 'Philadelphia Eagles', null, null, 'scheduled', false, null, 'AFC North', null),
('w14-titans-at-chargers', 'W14', 14, null, null, 'Los Angeles Chargers', 'Tennessee Titans', null, null, 'scheduled', false, true, 'AFC South', 'TNF'),
('w14-giants-at-chiefs', 'W14', 14, null, null, 'Kansas City Chiefs', 'New York Giants', null, null, 'scheduled', false, true, 'AFC West', 'MNF'),
('w14-commanders-at-colts', 'W14', 14, null, null, 'Indianapolis Colts', 'Washington Commanders', null, null, 'scheduled', false, null, 'AFC South', null),
('w14-lions-at-falcons', 'W14', 14, null, null, 'Atlanta Falcons', 'Detroit Lions', null, null, 'scheduled', false, null, 'NFC North', null),
('w14-raiders-at-jaguars', 'W14', 14, null, null, 'Jacksonville Jaguars', 'Las Vegas Raiders', null, null, 'scheduled', false, true, 'AFC South', 'SNF'),
('w14-panthers-at-jets', 'W14', 14, null, null, 'New York Jets', 'Carolina Panthers', null, null, 'scheduled', false, null, 'AFC East', null),
('w14-steelers-at-packers', 'W14', 14, null, null, 'Green Bay Packers', 'Pittsburgh Steelers', null, null, 'scheduled', false, null, 'AFC North', null),
('w14-cowboys-at-patriots', 'W14', 14, null, null, 'New England Patriots', 'Dallas Cowboys', null, null, 'scheduled', false, null, 'AFC East', null),
('w14-saints-at-rams', 'W14', 14, null, null, 'Los Angeles Rams', 'New Orleans Saints', null, null, 'scheduled', false, null, 'NFC South', null),
('w14-buccaneers-at-ravens', 'W14', 14, null, null, 'Baltimore Ravens', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, null, 'AFC North', null),
('w14-cardinals-at-texans', 'W14', 14, null, null, 'Houston Texans', 'Arizona Cardinals', null, null, 'scheduled', false, null, 'AFC South', null),
('w14-bills-at-vikings', 'W14', 14, null, null, 'Minnesota Vikings', 'Buffalo Bills', null, null, 'scheduled', false, null, 'AFC East', null),
('w15-buccaneers-at-49ers', 'W15', 15, null, null, 'San Francisco 49ers', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, null, 'NFC South', null),
('w15-giants-at-bengals', 'W15', 15, null, null, 'Cincinnati Bengals', 'New York Giants', null, null, 'scheduled', false, null, 'AFC North', null),
('w15-jaguars-at-broncos', 'W15', 15, null, null, 'Denver Broncos', 'Jacksonville Jaguars', null, null, 'scheduled', false, null, 'AFC South', null),
('w15-chargers-at-browns', 'W15', 15, null, null, 'Cleveland Browns', 'Los Angeles Chargers', null, null, 'scheduled', false, null, 'AFC North', null),
('w15-bears-at-chiefs', 'W15', 15, null, null, 'Kansas City Chiefs', 'Chicago Bears', null, null, 'scheduled', false, null, 'AFC West', null),
('w15-packers-at-colts', 'W15', 15, null, null, 'Indianapolis Colts', 'Green Bay Packers', null, null, 'scheduled', false, null, 'AFC South', null),
('w15-jets-at-commanders', 'W15', 15, null, null, 'Washington Commanders', 'New York Jets', null, null, 'scheduled', false, null, 'AFC East', null),
('w15-ravens-at-cowboys', 'W15', 15, null, null, 'Dallas Cowboys', 'Baltimore Ravens', null, null, 'scheduled', false, null, 'AFC North', null),
('w15-panthers-at-dolphins', 'W15', 15, null, null, 'Miami Dolphins', 'Carolina Panthers', null, null, 'scheduled', false, null, 'AFC East', null),
('w15-titans-at-eagles', 'W15', 15, null, null, 'Philadelphia Eagles', 'Tennessee Titans', null, null, 'scheduled', false, null, 'AFC South', null),
('w15-raiders-at-falcons', 'W15', 15, null, null, 'Atlanta Falcons', 'Las Vegas Raiders', null, null, 'scheduled', false, null, 'AFC West', null),
('w15-patriots-at-lions', 'W15', 15, null, null, 'Detroit Lions', 'New England Patriots', null, null, 'scheduled', false, null, 'AFC East', null),
('w15-bills-at-saints', 'W15', 15, null, null, 'New Orleans Saints', 'Buffalo Bills', null, null, 'scheduled', false, null, 'AFC East', null),
('w15-steelers-at-seahawks', 'W15', 15, null, null, 'Seattle Seahawks', 'Pittsburgh Steelers', null, null, 'scheduled', false, null, 'AFC North', null),
('w15-vikings-at-texans', 'W15', 15, null, null, 'Houston Texans', 'Minnesota Vikings', null, null, 'scheduled', false, null, 'AFC South', null),
('w16-vikings-at-bears', 'W16', 16, null, null, 'Chicago Bears', 'Minnesota Vikings', null, null, 'scheduled', false, null, 'NFC North', null),
('w16-ravens-at-bengals', 'W16', 16, null, null, 'Cincinnati Bengals', 'Baltimore Ravens', null, null, 'scheduled', false, null, 'AFC North', null),
('w16-rams-at-cardinals', 'W16', 16, null, null, 'Arizona Cardinals', 'Los Angeles Rams', null, null, 'scheduled', false, null, 'NFC West', null),
('w16-raiders-at-chargers', 'W16', 16, null, null, 'Los Angeles Chargers', 'Las Vegas Raiders', null, null, 'scheduled', false, null, 'AFC West', null),
('w16-broncos-at-chiefs', 'W16', 16, null, null, 'Kansas City Chiefs', 'Denver Broncos', null, null, 'scheduled', false, null, 'AFC West', null),
('w16-texans-at-colts', 'W16', 16, null, null, 'Indianapolis Colts', 'Houston Texans', null, null, 'scheduled', false, null, 'AFC South', null),
('w16-eagles-at-commanders', 'W16', 16, null, null, 'Washington Commanders', 'Philadelphia Eagles', null, null, 'scheduled', false, null, 'NFC East', null),
('w16-bills-at-dolphins', 'W16', 16, null, null, 'Miami Dolphins', 'Buffalo Bills', null, null, 'scheduled', false, null, 'AFC East', null),
('w16-buccaneers-at-falcons', 'W16', 16, null, null, 'Atlanta Falcons', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, null, 'NFC South', null),
('w16-cowboys-at-giants', 'W16', 16, null, null, 'New York Giants', 'Dallas Cowboys', null, null, 'scheduled', false, null, 'NFC East', null),
('w16-patriots-at-jets', 'W16', 16, null, null, 'New York Jets', 'New England Patriots', null, null, 'scheduled', false, null, 'AFC East', null),
('w16-packers-at-lions', 'W16', 16, null, null, 'Detroit Lions', 'Green Bay Packers', null, null, 'scheduled', false, null, 'NFC North', null),
('w16-saints-at-panthers', 'W16', 16, null, null, 'Carolina Panthers', 'New Orleans Saints', null, null, 'scheduled', false, null, 'NFC South', null),
('w16-49ers-at-seahawks', 'W16', 16, null, null, 'Seattle Seahawks', 'San Francisco 49ers', null, null, 'scheduled', false, null, 'NFC West', null),
('w16-browns-at-steelers', 'W16', 16, null, null, 'Pittsburgh Steelers', 'Cleveland Browns', null, null, 'scheduled', false, null, 'AFC North', null),
('w16-jaguars-at-titans', 'W16', 16, null, null, 'Tennessee Titans', 'Jacksonville Jaguars', null, null, 'scheduled', false, null, 'AFC South', null),
('w17-lions-at-bears', 'W17', 17, null, null, 'Chicago Bears', 'Detroit Lions', null, null, 'scheduled', false, null, 'NFC North', null),
('w17-ravens-at-browns', 'W17', 17, null, null, 'Cleveland Browns', 'Baltimore Ravens', null, null, 'scheduled', false, null, 'AFC North', null),
('w17-seahawks-at-cardinals', 'W17', 17, null, null, 'Arizona Cardinals', 'Seattle Seahawks', null, null, 'scheduled', false, null, 'NFC West', null),
('w17-chiefs-at-chargers', 'W17', 17, null, null, 'Los Angeles Chargers', 'Kansas City Chiefs', null, null, 'scheduled', false, null, 'AFC West', null),
('w17-giants-at-commanders', 'W17', 17, null, null, 'Washington Commanders', 'New York Giants', null, null, 'scheduled', false, null, 'NFC East', null),
('w17-cowboys-at-eagles', 'W17', 17, null, null, 'Philadelphia Eagles', 'Dallas Cowboys', null, null, 'scheduled', false, null, 'NFC East', null),
('w17-texans-at-jaguars', 'W17', 17, null, null, 'Jacksonville Jaguars', 'Houston Texans', null, null, 'scheduled', false, null, 'AFC South', null),
('w17-dolphins-at-jets', 'W17', 17, null, null, 'New York Jets', 'Miami Dolphins', null, null, 'scheduled', false, null, 'AFC East', null),
('w17-falcons-at-panthers', 'W17', 17, null, null, 'Carolina Panthers', 'Atlanta Falcons', null, null, 'scheduled', false, null, 'NFC South', null),
('w17-bills-at-patriots', 'W17', 17, null, null, 'New England Patriots', 'Buffalo Bills', null, null, 'scheduled', false, null, 'AFC East', null),
('w17-broncos-at-raiders', 'W17', 17, null, null, 'Las Vegas Raiders', 'Denver Broncos', null, null, 'scheduled', false, null, 'AFC West', null),
('w17-49ers-at-rams', 'W17', 17, null, null, 'Los Angeles Rams', 'San Francisco 49ers', null, null, 'scheduled', false, null, 'NFC West', null),
('w17-buccaneers-at-saints', 'W17', 17, null, null, 'New Orleans Saints', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, null, 'NFC South', null),
('w17-bengals-at-steelers', 'W17', 17, null, null, 'Pittsburgh Steelers', 'Cincinnati Bengals', null, null, 'scheduled', false, null, 'AFC North', null),
('w17-colts-at-titans', 'W17', 17, null, null, 'Tennessee Titans', 'Indianapolis Colts', null, null, 'scheduled', false, null, 'AFC South', null),
('w17-packers-at-vikings', 'W17', 17, null, null, 'Minnesota Vikings', 'Green Bay Packers', null, null, 'scheduled', false, null, 'NFC North', null),
('w18-packers-at-bears', 'W18', 18, null, null, 'Chicago Bears', 'Green Bay Packers', null, null, 'scheduled', false, null, 'NFC North', null),
('w18-bengals-at-browns', 'W18', 18, null, null, 'Cleveland Browns', 'Cincinnati Bengals', null, null, 'scheduled', false, null, 'AFC North', null),
('w18-49ers-at-cardinals', 'W18', 18, null, null, 'Arizona Cardinals', 'San Francisco 49ers', null, null, 'scheduled', false, null, 'NFC West', null),
('w18-broncos-at-chargers', 'W18', 18, null, null, 'Los Angeles Chargers', 'Denver Broncos', null, null, 'scheduled', false, null, 'AFC West', null),
('w18-cowboys-at-commanders', 'W18', 18, null, null, 'Washington Commanders', 'Dallas Cowboys', null, null, 'scheduled', false, null, 'NFC East', null),
('w18-giants-at-eagles', 'W18', 18, null, null, 'Philadelphia Eagles', 'New York Giants', null, null, 'scheduled', false, null, 'NFC East', null),
('w18-colts-at-jaguars', 'W18', 18, null, null, 'Jacksonville Jaguars', 'Indianapolis Colts', null, null, 'scheduled', false, null, 'AFC South', null),
('w18-bills-at-jets', 'W18', 18, null, null, 'New York Jets', 'Buffalo Bills', null, null, 'scheduled', false, null, 'AFC East', null),
('w18-buccaneers-at-panthers', 'W18', 18, null, null, 'Carolina Panthers', 'Tampa Bay Buccaneers', null, null, 'scheduled', false, null, 'NFC South', null),
('w18-dolphins-at-patriots', 'W18', 18, null, null, 'New England Patriots', 'Miami Dolphins', null, null, 'scheduled', false, null, 'AFC East', null),
('w18-chiefs-at-raiders', 'W18', 18, null, null, 'Las Vegas Raiders', 'Kansas City Chiefs', null, null, 'scheduled', false, null, 'AFC West', null),
('w18-seahawks-at-rams', 'W18', 18, null, null, 'Los Angeles Rams', 'Seattle Seahawks', null, null, 'scheduled', false, null, 'NFC West', null),
('w18-falcons-at-saints', 'W18', 18, null, null, 'New Orleans Saints', 'Atlanta Falcons', null, null, 'scheduled', false, null, 'NFC South', null),
('w18-ravens-at-steelers', 'W18', 18, null, null, 'Pittsburgh Steelers', 'Baltimore Ravens', null, null, 'scheduled', false, null, 'AFC North', null),
('w18-texans-at-titans', 'W18', 18, null, null, 'Tennessee Titans', 'Houston Texans', null, null, 'scheduled', false, null, 'AFC South', null),
('w18-lions-at-vikings', 'W18', 18, null, null, 'Minnesota Vikings', 'Detroit Lions', null, null, 'scheduled', false, null, 'NFC North', null);


insert into public.rankings (id, week, rank, team_name, previous_rank, note, updated_at, created_at)
values
('85acba99-0937-5e1b-bd05-4372973c2c4c', 3, 1, 'Pittsburgh Steelers', null, '', now(), now()),
('61cc23a2-f341-5031-89c7-c19e515cf7b7', 3, 2, 'Philadelphia Eagles', null, '', now(), now()),
('e5b582db-2694-5503-b3e6-2b01f2af8f87', 3, 3, 'New York Giants', null, '', now(), now()),
('d875e30f-7a7b-5afd-89f8-4639319dcdef', 3, 4, 'Cincinnati Bengals', null, '', now(), now()),
('56204f29-e7f2-5ce8-b569-e588261035da', 3, 5, 'Tennessee Titans', null, '', now(), now()),
('9b95c40e-1d93-5c18-a1c2-344e6324d448', 3, 6, 'Seattle Seahawks', null, '', now(), now()),
('0512435d-9b54-5d42-a833-3dfb6d6350c9', 3, 7, 'New Orleans Saints', null, '', now(), now()),
('0848335b-9e90-5aed-a1ea-16ec39f33599', 3, 8, 'Los Angeles Chargers', null, '', now(), now()),
('85d93a50-84e0-5e91-8f4c-df9e6ab43f33', 3, 9, 'Denver Broncos', null, '', now(), now()),
('c9e961b5-b29b-5797-9f3b-c8da266efd65', 3, 10, 'Buffalo Bills', null, '', now(), now()),
('2084e217-5a7e-5148-91aa-164508b22892', 3, 11, 'Kansas City Chiefs', null, '', now(), now()),
('405f6249-2a2f-5b26-976a-1f795ba96b9e', 3, 12, 'Cleveland Browns', null, '', now(), now()),
('cf257fe8-34d6-5876-9746-a066e37288df', 3, 13, 'Houston Texans', null, '', now(), now()),
('982879c2-722e-57d0-9b49-9f864b001dd2', 3, 14, 'Miami Dolphins', null, '', now(), now()),
('af23a1a2-28a2-5cfe-8d39-b1619962ff55', 3, 15, 'Minnesota Vikings', null, '', now(), now()),
('4f32d872-5a80-5cb4-9295-3ab6ba6985cf', 3, 16, 'Washington Commanders', null, '', now(), now()),
('fa747b15-3214-5fb4-97c8-63556017035c', 3, 17, 'New York Jets', null, '', now(), now()),
('ccee08d6-a2ad-5dca-8066-86697e37c6ad', 3, 18, 'Los Angeles Rams', null, '', now(), now()),
('3e24842c-3384-502c-a262-9acb7115d26b', 3, 19, 'Carolina Panthers', null, '', now(), now()),
('cbe87607-8f1b-5da1-97f1-2ffa0cf156fc', 3, 20, 'Baltimore Ravens', null, '', now(), now()),
('3c562c48-7870-5f9b-93cf-373a9989c90c', 3, 21, 'Detroit Lions', null, '', now(), now()),
('7d129f62-f06f-5fab-aa58-1f11cb3c1031', 3, 22, 'Tampa Bay Buccaneers', null, '', now(), now()),
('82a91579-c683-546f-b903-713e3aeb90a6', 3, 23, 'Las Vegas Raiders', null, '', now(), now()),
('7bed1ff0-34bc-5cb6-b4df-d70ec0c9bff7', 3, 24, 'Arizona Cardinals', null, '', now(), now()),
('9bc2dff4-126d-58e2-84f2-9b09641620f1', 3, 25, 'Dallas Cowboys', null, '', now(), now()),
('14206b6d-2d23-557a-9fdb-8722a33c251d', 3, 26, 'New England Patriots', null, '', now(), now()),
('aef5a84a-b07d-5d78-a2e0-e659c5927814', 3, 27, 'San Francisco 49ers', null, '', now(), now()),
('d7e69d57-f449-5a50-b9e6-be4dd03632da', 3, 28, 'Jacksonville Jaguars', null, '', now(), now()),
('25325557-69db-5d9e-bf20-8655e6531259', 3, 29, 'Atlanta Falcons', null, '', now(), now()),
('5d1d551f-6296-5712-b075-6aa7d155c992', 3, 30, 'Green Bay Packers', null, '', now(), now()),
('adc69dbb-07a5-55bb-a137-a7eb09bf2fba', 3, 31, 'Chicago Bears', null, '', now(), now()),
('cd3ee574-e9df-5d09-ba55-5dbb572f7d95', 3, 32, 'Indianapolis Colts', null, '', now(), now())
on conflict (id) do update set
  week = excluded.week,
  rank = excluded.rank,
  team_name = excluded.team_name,
  previous_rank = excluded.previous_rank,
  note = excluded.note,
  updated_at = excluded.updated_at,
  created_at = excluded.created_at;


insert into public.site_settings (key, value)
values
  ('rules', jsonb_build_object(
    'title', 'NTFL SEASON 3',
    'body', $$OFFICIAL RULES & POLICIES

JERSEYS & LOGOS

• The Home Team has first choice of uniform selection. If the Home Team elects to wear a colored jersey, the Away Team must wear white, and vice versa.

• Uniform selections must be submitted to the Commissioner before the weekly deadline. Failure to submit a request will result in the team's default Home/Away uniform being used.

• Available logos and uniform options are based on NFL uniforms worn during the 2024-25 and 2025-26 seasons. Uniforms not worn during those seasons will not be available at the launch of Season 3 but may be added in future updates.

• An official Uniform Directory will be provided listing all available Home, Away, Alternate, and Combo uniforms.

ALTERNATE UNIFORMS

• Alternate uniforms are intended to be used realistically and may not be excessively worn.

• Each franchise is limited to four (4) Alternate Uniform appearances per season.

• The four-use limit applies to all Alternate Uniforms combined, not each Alternate individually.

• Teams are responsible for monitoring and managing their Alternate Uniform usage.

UNIFORM COMBOS

• A Uniform Combo is a combination of approved jerseys, pants, and socks used by the real NFL franchise.

• Available Combo uniforms will be listed within the official Uniform Directory.

ACCOUNT POLICY

• Each franchise is permitted one (1) primary account and up to three (3) alternate accounts.

• Use of accounts beyond the league limit may result in penalties determined by league administration.

COMPETITIVE INTEGRITY

• The purchasing, botting, or artificial inflation of likes, votes, views, or engagement is strictly prohibited.

• Any engagement determined to be fraudulent will be removed from league records.

• Coaches found responsible for engagement manipulation will be subject to disciplinary action in accordance with league protocol.

• Fan accounts involved in engagement manipulation may face restrictions, removal, or other corrective actions as determined by league administration.

LEAGUE AUTHORITY

• NTFL Administration reserves the right to investigate suspicious activity, interpret league rules, and issue disciplinary action when necessary to preserve fairness, realism, and competitive integrity throughout the season.$$ 
  )),
  ('season_banner', jsonb_build_object('title', 'Season 3 Week 1', 'subtitle', 'NTFL Network')),
  ('home_banner', jsonb_build_object('headline', 'Where the NTFL collides', 'cta', 'Commissioner Control Center'))
on conflict (key) do update set value = excluded.value;

commit;
